# Generated by Django 6.0.2 on 2026-02-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('ELEVATED', 'Elevated'), ('BASIC', 'Basic')], db_index=True, default='BASIC', max_length=20),
        ),
    ]
