# Generated by Django 6.0.2 on 2026-02-09 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_role'),
    ]

    def update_roles(apps, schema_editor):
        CustomUser = apps.get_model('users', 'CustomUser')
        CustomUser.objects.filter(role='SUPERVISOR').update(role='ELEVATED')
        CustomUser.objects.filter(role='WORKER').update(role='BASIC')

    def reverse_roles(apps, schema_editor):
        CustomUser = apps.get_model('users', 'CustomUser')
        CustomUser.objects.filter(role='ELEVATED').update(role='SUPERVISOR')
        CustomUser.objects.filter(role='BASIC').update(role='WORKER')

    operations = [
        migrations.RunPython(update_roles, reverse_roles),
    ]
