# Generated by Django 6.0.2 on 2026-02-07 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_milestone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milestone',
            options={'ordering': ['deadline']},
        ),
        migrations.AlterModelOptions(
            name='projectsite',
            options={'ordering': ['-start_date']},
        ),
        migrations.AddField(
            model_name='milestone',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='milestone_images/'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectsite',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='projectsite',
            name='latitude',
            field=models.FloatField(help_text='Latitude for geolocation', validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='projectsite',
            name='longitude',
            field=models.FloatField(help_text='Longitude for geolocation', validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='projectsite',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['project', 'status'], name='projects_mi_project_dc545b_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['deadline'], name='projects_mi_deadlin_c1dc78_idx'),
        ),
        migrations.AddIndex(
            model_name='projectsite',
            index=models.Index(fields=['status'], name='projects_pr_status_98b10e_idx'),
        ),
        migrations.AddIndex(
            model_name='projectsite',
            index=models.Index(fields=['start_date'], name='projects_pr_start_d_a23149_idx'),
        ),
    ]
