# Generated by Django 6.0.2 on 2026-02-07 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_milestone_options_alter_projectsite_options_and_more'),
    ]

    operations = [
    ]
