# Generated by Django 6.0.2 on 2026-02-09 10:54

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_milestoneimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestoneimage',
            name='uploaded_at',
            field=models.DateTimeField(default=core.utils.get_ist_now, editable=False),
        ),
        migrations.AlterField(
            model_name='projectsite',
            name='start_date',
            field=models.DateField(default=core.utils.get_ist_date),
        ),
    ]
