# Generated by Django 6.0.2 on 2026-02-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_milestoneimage_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsite',
            name='site_radius',
            field=models.PositiveIntegerField(default=500, help_text='Proximity radius in meters for worker check-in'),
        ),
    ]
