# Generated by Django 6.0.2 on 2026-02-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemTaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('run_date', models.DateField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('task_name', 'run_date')},
            },
        ),
    ]
