# Generated by Django 6.0.2 on 2026-02-09 15:18

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemtasklog',
            name='completed_at',
            field=models.DateTimeField(default=core.utils.get_ist_now, editable=False),
        ),
    ]
