# Generated by Django 6.0.2 on 2026-02-09 02:58

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=core.utils.get_ist_now),
        ),
    ]
