# Generated by Django 6.0.2 on 2026-02-07 20:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0005_milestoneimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('fuel_type', models.CharField(choices=[('DIESEL', 'Diesel'), ('PETROL', 'Petrol'), ('CNG', 'CNG')], default='DIESEL', max_length=20)),
                ('quantity_liters', models.DecimalField(decimal_places=2, help_text='Quantity in liters', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('price_per_liter', models.DecimalField(decimal_places=2, help_text='Price per liter in INR', max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('vehicle_equipment', models.CharField(blank=True, help_text='Vehicle or equipment name/number', max_length=100)),
                ('entry_type', models.CharField(choices=[('EXPENSE', 'Expense'), ('THEFT', 'Theft')], db_index=True, default='EXPENSE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_records', to='projects.projectsite')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['project', 'entry_type'], name='fuel_fuelre_project_831a9d_idx'), models.Index(fields=['date'], name='fuel_fuelre_date_e074f1_idx'), models.Index(fields=['fuel_type'], name='fuel_fuelre_fuel_ty_ecf44f_idx')],
            },
        ),
    ]
