# Generated by Django 6.0.2 on 2026-02-07 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelrecord',
            name='vehicle_equipment',
        ),
        migrations.AddField(
            model_name='fuelrecord',
            name='vehicle',
            field=models.ForeignKey(blank=True, help_text='Select vehicle or equipment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_records', to='vehicles.vehicle'),
        ),
    ]
