# Generated by Django 6.0.2 on 2026-02-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0002_remove_fuelrecord_vehicle_equipment_and_more'),
        ('projects', '0005_milestoneimage'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fuelrecord',
            name='fuel_fuelre_project_831a9d_idx',
        ),
        migrations.AddIndex(
            model_name='fuelrecord',
            index=models.Index(fields=['project'], name='fuel_fuelre_project_f89658_idx'),
        ),
        migrations.RemoveField(
            model_name='fuelrecord',
            name='entry_type',
        ),
    ]
