# Generated by Django 6.0.2 on 2026-02-08 08:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0003_remove_fuelrecord_fuel_fuelre_project_831a9d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelrecord',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='fuel_receipts/'),
        ),
        migrations.AlterField(
            model_name='fuelrecord',
            name='price_per_liter',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per liter in INR', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='fuelrecord',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount paid', max_digits=12),
        ),
    ]
