# Generated by Django 6.0.2 on 2026-02-09 10:54

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0004_fuelrecord_receipt_alter_fuelrecord_price_per_liter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelrecord',
            name='created_at',
            field=models.DateTimeField(default=core.utils.get_ist_now, editable=False),
        ),
        migrations.AlterField(
            model_name='fuelrecord',
            name='date',
            field=models.DateField(default=core.utils.get_ist_date),
        ),
        migrations.AlterField(
            model_name='fuelrecord',
            name='updated_at',
            field=models.DateTimeField(default=core.utils.get_ist_now),
        ),
    ]
