# Generated by Django 6.0.2 on 2026-02-09 19:03

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0005_alter_fuelrecord_created_at_alter_fuelrecord_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelRecordImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fuel_receipts/')),
                ('uploaded_at', models.DateTimeField(default=core.utils.get_ist_now, editable=False)),
                ('fuel_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='fuel.fuelrecord')),
            ],
        ),
    ]
