# Generated by Django 6.0.2 on 2026-02-07 20:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0005_milestoneimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('TRUCK', 'Truck'), ('EXCAVATOR', 'Excavator'), ('CRANE', 'Crane'), ('LOADER', 'Loader'), ('OTHER', 'Other')], default='TRUCK', max_length=20)),
                ('asset_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'Maintenance'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles', to='projects.projectsite')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='vehicles_ve_status_f71f77_idx'), models.Index(fields=['assigned_site'], name='vehicles_ve_assigne_574017_idx'), models.Index(fields=['vehicle_type'], name='vehicles_ve_vehicle_76fbe4_idx')],
            },
        ),
    ]
