# Generated by Django 6.0.2 on 2026-02-09 10:54

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(default=core.utils.get_ist_now, editable=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(default=core.utils.get_ist_now),
        ),
    ]
