# Generated by Django 6.0.2 on 2026-02-07 14:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        ('projects', '0003_alter_milestone_options_alter_projectsite_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', '-check_in_time']},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LEAVE', 'On Leave')], db_index=True, default='ABSENT', max_length=10),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['worker', 'date'], name='attendance__worker__654811_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['site', 'date'], name='attendance__site_id_5adfbf_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status'], name='attendance__status_132c06_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='attendance__date_61f2e1_idx'),
        ),
    ]
