# Generated by Django 6.0.2 on 2026-02-09 15:18

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_in_time',
            field=models.DateTimeField(blank=True, default=core.utils.get_ist_now, null=True),
        ),
    ]
